services:
#  payment-proxy-1:
#    image: payment-proxy:0.0.1-SNAPSHOT
#    ports:
#      - 9999:9999
#    deploy:
#      resources:
#        limits:
#          cpus: 0.15
#          memory: 42MB
  redis:
    image: redis:7.2-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - 6379:6379
#    networks:
#      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"