services:
  nginx:
    image: nginx:alpine
    ports:
      - 9999:9999
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: 0.2
          memory: 44MB
    depends_on:
      - payment-proxy-1
      - payment-proxy-2

  payment-proxy-1:
    image: payment-proxy:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128MB
    networks:
      - backend
      - payment-processor
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - WEB_CLIENT_POOL_SIZE=32
      - WEB_CLIENT_PENDING_ACQUIRE_MAX_COUNT=512
      - WEB_CLIENT_TIMEOUT=-1
      - REDIS_POOL_MAX_ACTIVE=8
      - REDIS_POOL_MAX_IDLE=4
      - REDIS_POOL_MIN_IDLE=4
      - JETTY_THREADS_ACCEPTORS=-1
      - CONSUMER_THREAD_POOL=500
    depends_on:
      redis:
        condition: service_healthy

  payment-proxy-2:
    image: payment-proxy:0.0.1-SNAPSHOT
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 128MB
    networks:
      - backend
      - payment-processor
    environment:
      - DEFAULT_URL=http://payment-processor-default:8080
      - FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - WEB_CLIENT_POOL_SIZE=32
      - WEB_CLIENT_PENDING_ACQUIRE_MAX_COUNT=512
      - WEB_CLIENT_TIMEOUT=-1
      - REDIS_POOL_MAX_ACTIVE=8
      - REDIS_POOL_MAX_IDLE=4
      - REDIS_POOL_MIN_IDLE=4
      - JETTY_THREADS_ACCEPTORS=-1
      - CONSUMER_THREAD_POOL=500
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - ./docker/redis-init.sh:/usr/local/bin/redis-init.sh:ro
    entrypoint: [ "sh", "-c", "/usr/local/bin/redis-init.sh" ]
    ports:
      - 6379:6379
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
    deploy:
      resources:
        limits:
          cpus: 0.3
          memory: 50MB

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true